@startuml
left to right direction

!includeurl https://raw.githubusercontent.com/wonderbird/generator-kata-net-core/master/doc/plantuml-style.puml

[**GeneratorKataNetCore**\n\n//Main entrypoint - This generator//\n//is called by Yeoman//] as gen
[Configuration\n\n//Store configuration and//\n//answers to the prompts//] as config

[Generator Classes\n\n//Dedicated classes to generate//\n//dotnet solution, class library,//\n//test project etc.//] as genclasses

[DotnetCli\n\n//Wrapper for the .NET Core//\n//command line interface//] as dotnet
[FileSystem\n\n//Encapsulate Yeoman//\n//filesystem access//] as fs
[DateUtils\n\n//Encapsulate JavaScript//\n//Date utilities//] as date

gen *- config
gen *-- genclasses

genclasses -- fs
config -right- date

genclasses -- dotnet
@enduml
