:gitplant: http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/wonderbird/generator-kata-net-core/master/doc/

== Technical Context

[caption="Technical Context"]
image::{gitplant}/technical-context.puml[Technical Context Diagram]

The following external tools colaborate with this `generator-kata-net-core` project in order to create .NET Core solutions:

[options="header",cols="1,2,2"]
|===
|External Component|Role|Interface documentation
|Yeoman
|Generic scaffolding tool for software projects
|https://yeoman.io/authoring/index.html

|.NET Core CLI
|Command line interface application used to generate .NET Core solutions, projects and to build, run and test .NET Core solutions
|https://docs.microsoft.com/en-us/dotnet/core/tools/
|===

== Composite Structure

The inner structure of this `generator-kata-net-core` project is depicted here:

[caption="Composite Structure of the Generator"]
image::{gitplant}/composite-structure.puml[Composite Structure Diagram]

Yeoman uses the `GeneratorKataNetCore` class as its main entrypoint. Details about the interface are documentend on the https://yeoman.io/authoring/index.html[yeoman homepage]. This class is located in the link:app/index.js[app/index.js] file - the file names of all other classes match the class names.

The parameters entered by the user are collected in the `Configuration`. This object also holds information about the system, e.g. the current year.

`GeneratorKataNetCore` then calls the `Generator Classes` individually in the correct sequence and passes the `Configuration` down to them.

The `Generator Classes` use the .NET Core CLI to create the required .NET project elements. They use the `FileSystem` wrapper in order to copy `Template Files`. The values of the `Configuration` are used to replace the placeholders contained in the `Template Files`.

The following diagram shows the generator classes used by `GeneratorKataNetCore` sequentially in order to create the solution, class library and other stuff.

[caption="Generator Classes"]
image::{gitplant}/generator-classes.puml[Generator Classes]

