@startuml

!includeurl https://raw.githubusercontent.com/wonderbird/generator-kata-net-core/master/doc/plantuml-style.puml

legend
**Legend**

<back:White>            </back> External system

<back:LightSkyBlue>            </back> System in this repository

A --    -- B The external system is interacting with the system in this repository
end legend

[Yeoman\n\n//Software project generator//] as yo
[generator-kata-net-core\n\n//.NET Core project generator//] as gen #LightSkyBlue
[dotnet CLI\n\n//Command line interface//\n//to generate .NET artifacts//] as dotnet

yo - gen
gen - dotnet

@enduml