# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        GIT_COMMIT_SHA: $GITHUB_SHA
        GIT_BRANCH: $GITHUB_REF
        VELOCITY_TEST_REPORTER_ID: feb2db939b4dc14d79333f2ef4427981596ca8d25a2a64fdc87d9bb82815b40a
    - run: npm run lint
    - run: npm run complexity
    - name: Archive complexity reports
      uses: actions/upload-artifact@v2
      with:
        name: complexity-reports
        path: .complexity-report/

  coverage:
    needs: [ build ]
    name: coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '12'
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: feb2db939b4dc14d79333f2ef4427981596ca8d25a2a64fdc87d9bb82815b40a
      with:
        coverageCommand: npm run coverage
  